version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: autostock_db
      POSTGRES_USER: autostock
      POSTGRES_PASSWORD: autostock_password
      POSTGRES_INITDB_ARGS: "--auth-host=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autostock -d autostock_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://autostock:autostock_password@postgres:5432/autostock_db
      JWT_SECRET: your-super-secret-jwt-signing-key-minimum-32-characters-for-production
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
