services:
  - type: web
    name: autostock-backend
    env: node
    buildCommand: npm run deploy:build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: autostock-db
          property: connectionString
  
  - type: pserv
    name: autostock-db
    env: postgresql
    plan: starter
    postgresMajorVersion: 15
