services:
  - type: web
    name: autostock-backend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://autostock-frontend-aiqqdaxlt-suras-projects-1078d583.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: autostock-db
          property: connectionString
  
  - type: pserv
    name: autostock-db
    env: postgresql
    plan: starter
    startCommand: echo "PostgreSQL service started"
